package org.shadowmaster435.lexer

enum class LexerGroupType {
    NONE,

    EXPRESSION_GROUP,
    METHOD_TUPLES,
    CONSTRUCTOR_TUPLES,
    METHOD_CALL_PARAMS,
    STRUCT_BODY,
    CLASS_BODY,
    FUNCTION_BODY,
    LAMBDA_BODY,
    LAMBDA_PARAMS,
    STRING_TEMPLATE,

    STRING,

    ARRAY_ACCESS,

    CLASS_POLYMORPHIC_DEFINITION,
    FUNCTION_POLYMORPHIC_DEFINITION,
    POLYMORPHIC_TYPE_INPUT
}