package org.shadowmaster435.tokenizer

// by bit index from left to right
// flags: 0: user defined, 1: is unary, 2: is optionally unary
enum class TokenType(vararg val subtypes: TokenSubtype) {
    OR(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    IS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    AS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    AT(TokenSubtype.OPERATOR, TokenSubtype.LEFT_OPERATOR),
    ADD(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    SUB(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OR_LEFT_OPERATOR),
    DIV(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    MUL(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    MOD(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    NOT(TokenSubtype.OPERATOR, TokenSubtype.LEFT_OPERATOR),
    SHL(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    SHR(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    POW(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    INC(TokenSubtype.OPERATOR, TokenSubtype.LEFT_OR_RIGHT_OPERATOR),
    DEC(TokenSubtype.OPERATOR, TokenSubtype.LEFT_OR_RIGHT_OPERATOR),
    AND(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    XOR(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    USHR(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    ADD_ASSIGN(TokenSubtype.OPERATOR, TokenSubtype.ASSIGNMENT, TokenSubtype.BINARY_OPERATOR),
    SUB_ASSIGN(TokenSubtype.OPERATOR, TokenSubtype.ASSIGNMENT, TokenSubtype.BINARY_OPERATOR),
    DIV_ASSIGN(TokenSubtype.OPERATOR, TokenSubtype.ASSIGNMENT, TokenSubtype.BINARY_OPERATOR),
    MUL_ASSIGN(TokenSubtype.OPERATOR, TokenSubtype.ASSIGNMENT, TokenSubtype.BINARY_OPERATOR),
    MOD_ASSIGN(TokenSubtype.OPERATOR, TokenSubtype.ASSIGNMENT, TokenSubtype.BINARY_OPERATOR),
    BIT_AND(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    BIT_OR(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    BIT_NOT(TokenSubtype.OPERATOR, TokenSubtype.LEFT_OPERATOR),
    NOT_NULL(TokenSubtype.OPERATOR, TokenSubtype.RIGHT_OPERATOR),

    CHAR(TokenSubtype.OTHER),
    STRING(TokenSubtype.OTHER),
    DOLLAR_SIGN(TokenSubtype.OPERATOR, TokenSubtype.LEFT_OPERATOR),
    IS_NOT(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    SAFE_AS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    ASSIGN(TokenSubtype.OPERATOR, TokenSubtype.ASSIGNMENT, TokenSubtype.BINARY_OPERATOR),
    ACCESS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    NULLABLE_ACCESS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    NULLABLE(TokenSubtype.OPERATOR, TokenSubtype.RIGHT_OPERATOR),
    ELVIS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    EQUAL(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    NOT_EQUAL(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    REF_EQUAL(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    REF_NOT_EQUAL(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    GREATER_EQ(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    LESS_EQ(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    LESS(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    GREATER(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    SEMICOLON(TokenSubtype.OPERATOR, TokenSubtype.BINARY_OPERATOR),
    LAMBDA_LEFT(TokenSubtype.OPERATOR),
    LAMBDA_RIGHT(TokenSubtype.OPERATOR),
    METHOD_CALL(TokenSubtype.OPERATOR, TokenSubtype.RIGHT_OPERATOR),
    COMMENT(TokenSubtype.OTHER),
    INLINE_BREAK(TokenSubtype.WHITESPACE),
    COMMA(TokenSubtype.OTHER),
    BACKSLASH(TokenSubtype.OTHER),
    OPEN_PARENTHESIS(TokenSubtype.GROUP_START),
    CLOSE_PARENTHESIS(TokenSubtype.GROUP_END),
    OPEN_BRACE(TokenSubtype.GROUP_START),
    CLOSE_BRACE(TokenSubtype.GROUP_END),
    OPEN_BRACKET(TokenSubtype.GROUP_START),
    CLOSE_BRACKET(TokenSubtype.GROUP_END),


    SPACE(TokenSubtype.WHITESPACE),
    OP_WORD(TokenSubtype.OPERATOR),
    DEFINE(TokenSubtype.KEYWORD),
    TYPE(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    KEYWORD(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    UNDEFINE(TokenSubtype.KEYWORD),
    CLASS(TokenSubtype.KEYWORD),
    GLOBAL(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    FILE(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    FINAL(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    VAL(TokenSubtype.KEYWORD),
    VAR(TokenSubtype.KEYWORD),
    CONST(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    NULL(TokenSubtype.CONSTABLE),
    IMPORT(TokenSubtype.KEYWORD),
    PACKAGE(TokenSubtype.KEYWORD),
    ENUM(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    INTERFACE(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    ABSTRACT(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    VARARG(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    OVERRIDE(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    PRIVATE(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    STRUCT(TokenSubtype.KEYWORD),
    PROTECTED(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    PUBLIC(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    STATIC(TokenSubtype.KEYWORD, TokenSubtype.MODIFIER),
    OBJECT(TokenSubtype.KEYWORD),
    THIS(TokenSubtype.KEYWORD),
    FUNC(TokenSubtype.KEYWORD),
    IF(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD, TokenSubtype.FLOW_CONTROL),
    ELSE(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD, TokenSubtype.FLOW_CONTROL),
    TRUE(TokenSubtype.CONSTABLE),
    FALSE(TokenSubtype.CONSTABLE),
    TRY(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD, TokenSubtype.FLOW_CONTROL),
    CATCH(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD, TokenSubtype.FLOW_CONTROL),
    FINALLY(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD, TokenSubtype.FLOW_CONTROL),
    WHEN(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD, TokenSubtype.FLOW_CONTROL),
    WHERE(TokenSubtype.KEYWORD),
    WHILE(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD),
    DO(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD),
    FOR(TokenSubtype.STATEMENT, TokenSubtype.KEYWORD),
    RETURN(TokenSubtype.FLOW_CONTROL, TokenSubtype.KEYWORD),
    BREAK(TokenSubtype.FLOW_CONTROL, TokenSubtype.KEYWORD),
    CONTINUE(TokenSubtype.FLOW_CONTROL, TokenSubtype.KEYWORD),
    NEWLINE(TokenSubtype.WHITESPACE),
    GENERIC(TokenSubtype.OTHER),
    NONE(TokenSubtype.NONE),
    ANY(TokenSubtype.OTHER);
    val isOperator = subtypes.contains(TokenSubtype.OPERATOR)

    enum class TokenSubtype {
        STATEMENT,
        FLOW_CONTROL,
        CONSTABLE,
        GROUP_START,
        GROUP_END,
        OPERATOR,
        LEFT_OPERATOR,
        RIGHT_OPERATOR,
        LEFT_OR_RIGHT_OPERATOR,
        BINARY_OPERATOR,
        BINARY_OR_LEFT_OPERATOR,
        WHITESPACE,
        KEYWORD,
        MODIFIER,
        OTHER,
        ASSIGNMENT,
        NONE
    }


}