package org.shadowmaster435.util

abstract class BindableFunction<A, T: Function<A>> private constructor(private val func: T, val argCount: Int) : () -> A {

    protected abstract val args: Array<Any?>

    abstract override operator fun invoke() : A

    fun bind(vararg args: Any?) {
        args.forEachIndexed { index, any ->
            this.args[index] = any
        }
    }
    
    @Suppress("UNCHECKED_CAST")
    companion object {
        operator fun <A> invoke(func: () -> A) : BindableFunction<A, () -> A> = object : BindableFunction<A, () -> A>(func, 0) {override val args = arrayOfNulls<Any?>(0);override fun invoke() = func.invoke()}
        operator fun <A,B> invoke(func: (B) -> A) : BindableFunction<A, (B) -> A> = object : BindableFunction<A, (B) -> A>(func, 1){override val args = arrayOfNulls<Any?>(1);override fun invoke() = func.invoke(args[0]as B)}
        operator fun <A,B,C> invoke(func: (B,C) -> A) : BindableFunction<A, (B,C) -> A> = object : BindableFunction<A, (B,C) -> A>(func, 2){override val args = arrayOfNulls<Any?>(2);override fun invoke() = func.invoke(args[0]as B,args[1]as C)}
        operator fun <A,B,C,D> invoke(func: (B,C,D) -> A) : BindableFunction<A, (B,C,D) -> A> = object : BindableFunction<A, (B,C,D) -> A>(func, 3){override val args = arrayOfNulls<Any?>(3);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D)}
        operator fun <A,B,C,D,E> invoke(func: (B,C,D,E) -> A) : BindableFunction<A, (B,C,D,E) -> A> = object : BindableFunction<A, (B,C,D,E) -> A>(func, 4){override val args = arrayOfNulls<Any?>(4);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E)}
        operator fun <A,B,C,D,E,F> invoke(func: (B,C,D,E,F) -> A) : BindableFunction<A, (B,C,D,E,F) -> A> = object : BindableFunction<A, (B,C,D,E,F) -> A>(func, 5){override val args = arrayOfNulls<Any?>(5);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F)}
        operator fun <A,B,C,D,E,F,G> invoke(func: (B,C,D,E,F,G) -> A) : BindableFunction<A, (B,C,D,E,F,G) -> A> = object : BindableFunction<A, (B,C,D,E,F,G) -> A>(func, 6){override val args = arrayOfNulls<Any?>(6);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G)}
        operator fun <A,B,C,D,E,F,G,H> invoke(func: (B,C,D,E,F,G,H) -> A) : BindableFunction<A, (B,C,D,E,F,G,H) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H) -> A>(func, 7){override val args = arrayOfNulls<Any?>(7);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H)}
        operator fun <A,B,C,D,E,F,G,H,I> invoke(func: (B,C,D,E,F,G,H,I) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I) -> A>(func, 8){override val args = arrayOfNulls<Any?>(8);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I)}
        operator fun <A,B,C,D,E,F,G,H,I,J> invoke(func: (B,C,D,E,F,G,H,I,J) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J) -> A>(func, 9){override val args = arrayOfNulls<Any?>(9);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K> invoke(func: (B,C,D,E,F,G,H,I,J,K) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K) -> A>(func, 10){override val args = arrayOfNulls<Any?>(10);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L> invoke(func: (B,C,D,E,F,G,H,I,J,K,L) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L) -> A>(func, 11){override val args = arrayOfNulls<Any?>(11);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M) -> A>(func, 12){override val args = arrayOfNulls<Any?>(12);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N) -> A>(func, 13){override val args = arrayOfNulls<Any?>(13);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O) -> A>(func, 14){override val args = arrayOfNulls<Any?>(14);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) -> A>(func, 15){override val args = arrayOfNulls<Any?>(15);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q) -> A>(func, 16){override val args = arrayOfNulls<Any?>(16);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R) -> A>(func, 17){override val args = arrayOfNulls<Any?>(17);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S) -> A>(func, 18){override val args = arrayOfNulls<Any?>(18);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R,args[17]as S)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T) -> A>(func, 19){override val args = arrayOfNulls<Any?>(19);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R,args[17]as S,args[18]as T)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U) -> A>(func, 20){override val args = arrayOfNulls<Any?>(20);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R,args[17]as S,args[18]as T,args[19]as U)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V) -> A>(func, 21){override val args = arrayOfNulls<Any?>(21);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R,args[17]as S,args[18]as T,args[19]as U,args[20]as V)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W) -> A>(func, 22){override val args = arrayOfNulls<Any?>(22);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R,args[17]as S,args[18]as T,args[19]as U,args[20]as V,args[21]as W)}
        operator fun <A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X> invoke(func: (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X) -> A) : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X) -> A> = object : BindableFunction<A, (B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X) -> A>(func, 23){override val args = arrayOfNulls<Any?>(23);override fun invoke() = func.invoke(args[0]as B,args[1]as C,args[2]as D,args[3]as E,args[4]as F,args[5]as G,args[6]as H,args[7]as I,args[8]as J,args[9]as K,args[10]as L,args[11]as M,args[12]as N,args[13]as O,args[14]as P,args[15]as Q,args[16]as R,args[17]as S,args[18]as T,args[19]as U,args[20]as V,args[21]as W,args[22]as X)}
    }

}